version: '3.3'

services:
        db:
                image: mysql:5.7
                command: --innodb-use-native-aio=0
                container_name: servidor_mysql
                volumes:
                        - "/home/ctamayo/algaworks/databases/mysql:/var/lib/mysql"
                tty: true
                ports:
                        - "3306:3306"
                expose:
                        - "3306"
                environment:
                        MYSQL_ROOT_USER: root
                        MYSQL_ROOT_PASSWORD: secret
                        MYSQL_DATABASE: restfood
                        MYSQL_USER: developer
                        MYSQL_PASSWORD: 123456
